-- Migration: Create category_type table and establish relationship with template table
-- Description: Creates the category_type table and adds foreign key relationship to template table
-- Date: 2025-01-XX

-- Step 1: Create category_type table
CREATE TABLE IF NOT EXISTS "category_type" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    icon BYTEA NOT NULL,
    "mimeType" VARCHAR(255),
    "originalFileName" VARCHAR(255),
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP,
    "deletedAt" TIMESTAMP
);

-- Step 2: Create index on name for faster lookups
CREATE INDEX IF NOT EXISTS "IDX_category_type_name" ON "category_type"(name);

-- Step 3: Create index on deletedAt for soft delete queries
CREATE INDEX IF NOT EXISTS "IDX_category_type_deletedAt" ON "category_type"("deletedAt") WHERE "deletedAt" IS NULL;

-- Step 4: Add new categoryTypeId column to template table (nullable initially for migration)
ALTER TABLE "template" 
ADD COLUMN IF NOT EXISTS "categoryTypeId" INT;

-- Step 5: Create foreign key constraint
ALTER TABLE "template"
ADD CONSTRAINT IF NOT EXISTS "FK_template_category_type" 
FOREIGN KEY ("categoryTypeId") REFERENCES "category_type"(id) ON DELETE SET NULL;

-- Step 6: Create index on foreign key for performance
CREATE INDEX IF NOT EXISTS "IDX_template_categoryTypeId" ON "template"("categoryTypeId");

-- Step 7: Add comments
COMMENT ON TABLE "category_type" IS 'Stores category types for notification templates';
COMMENT ON COLUMN "category_type".name IS 'Unique name of the category type';
COMMENT ON COLUMN "category_type".icon IS 'Binary icon data for the category type';
COMMENT ON COLUMN "category_type"."mimeType" IS 'MIME type of the icon (e.g., image/png, image/svg+xml)';
COMMENT ON COLUMN "category_type"."originalFileName" IS 'Original filename of the uploaded icon';
COMMENT ON COLUMN "template"."categoryTypeId" IS 'Foreign key reference to category_type table';

