-- ============================================================================
-- Complete Category Type Migration Script
-- ============================================================================
-- This script migrates the database to support category types
-- It's safe to run multiple times (idempotent) - checks before creating/adding
-- 
-- Order of execution:
--   1. Create category_type table
--   2. Add categoryTypeId column to template table
--   3. Create foreign key constraint
--   4. Create indexes for performance
--   5. Add table/column comments
--
-- Usage:
--   psql -U <username> -d <database> -f apps/backend/scripts/migrate-category-type-complete.sql
-- 
-- Or via Docker:
--   docker exec -i <container-name> psql -U <username> -d <database> < apps/backend/scripts/migrate-category-type-complete.sql
-- ============================================================================

\echo '🔄 Starting category type migration...'
\echo ''

-- ============================================================================
-- STEP 1: Create category_type table
-- ============================================================================
\echo '📦 Step 1: Creating category_type table...'

CREATE TABLE IF NOT EXISTS "category_type" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    icon BYTEA NOT NULL,
    "mimeType" VARCHAR(255),
    "originalFileName" VARCHAR(255),
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP,
    "deletedAt" TIMESTAMP
);

\echo '   ✅ category_type table created'
\echo ''

-- ============================================================================
-- STEP 2: Create indexes on category_type table
-- ============================================================================
\echo '📊 Step 2: Creating indexes on category_type...'

-- Index on name for faster lookups
CREATE INDEX IF NOT EXISTS "IDX_category_type_name" ON "category_type"(name);

-- Index on deletedAt for soft delete queries (partial index)
CREATE INDEX IF NOT EXISTS "IDX_category_type_deletedAt" 
ON "category_type"("deletedAt") 
WHERE "deletedAt" IS NULL;

\echo '   ✅ Indexes created'
\echo ''

-- ============================================================================
-- STEP 3: Add categoryTypeId column to template table
-- ============================================================================
\echo '🔗 Step 3: Adding categoryTypeId column to template table...'

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'template'
        AND column_name = 'categoryTypeId'
    ) THEN
        ALTER TABLE template
        ADD COLUMN "categoryTypeId" INTEGER NULL;
        
        RAISE NOTICE '   ✅ Column categoryTypeId added to template table';
    ELSE
        RAISE NOTICE '   ℹ️  Column categoryTypeId already exists';
    END IF;
END $$;

\echo ''

-- ============================================================================
-- STEP 4: Create index on categoryTypeId for performance
-- ============================================================================
\echo '📊 Step 4: Creating index on template.categoryTypeId...'

CREATE INDEX IF NOT EXISTS "IDX_template_categoryTypeId" ON "template"("categoryTypeId");

\echo '   ✅ Index created'
\echo ''

-- ============================================================================
-- STEP 5: Add foreign key constraint
-- ============================================================================
\echo '🔗 Step 5: Adding foreign key constraint...'

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_template_category_type'
        AND table_name = 'template'
        AND constraint_type = 'FOREIGN KEY'
    ) THEN
        ALTER TABLE template
        ADD CONSTRAINT fk_template_category_type
        FOREIGN KEY ("categoryTypeId")
        REFERENCES category_type(id)
        ON DELETE SET NULL;
        
        RAISE NOTICE '   ✅ Foreign key constraint fk_template_category_type created';
    ELSE
        RAISE NOTICE '   ℹ️  Foreign key constraint fk_template_category_type already exists';
    END IF;
END $$;

\echo ''

-- ============================================================================
-- STEP 6: Add table and column comments
-- ============================================================================
\echo '📝 Step 6: Adding comments...'

COMMENT ON TABLE "category_type" IS 'Stores category types for notification templates';
COMMENT ON COLUMN "category_type".name IS 'Unique name of the category type';
COMMENT ON COLUMN "category_type".icon IS 'Binary icon data for the category type';
COMMENT ON COLUMN "category_type"."mimeType" IS 'MIME type of the icon (e.g., image/png, image/svg+xml)';
COMMENT ON COLUMN "category_type"."originalFileName" IS 'Original filename of the uploaded icon';
COMMENT ON COLUMN "template"."categoryTypeId" IS 'Foreign key reference to category_type table';

\echo '   ✅ Comments added'
\echo ''

-- ============================================================================
-- STEP 7: Verification
-- ============================================================================
\echo '✅ Step 7: Verifying migration...'
\echo ''

-- Verify category_type table exists
SELECT 
    'Table Check' AS check_type,
    CASE 
        WHEN EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'category_type')
        THEN '✅ category_type table exists'
        ELSE '❌ category_type table missing'
    END AS status;

-- Verify categoryTypeId column exists
SELECT 
    'Column Check' AS check_type,
    column_name,
    data_type,
    is_nullable
FROM information_schema.columns
WHERE table_name = 'template'
    AND column_name = 'categoryTypeId';

-- Verify foreign key constraint
SELECT 
    'Foreign Key Check' AS check_type,
    tc.constraint_name,
    kcu.column_name,
    ccu.table_name AS foreign_table_name,
    ccu.column_name AS foreign_column_name,
    rc.delete_rule
FROM information_schema.table_constraints AS tc
JOIN information_schema.key_column_usage AS kcu
    ON tc.constraint_name = kcu.constraint_name
    AND tc.table_schema = kcu.table_schema
JOIN information_schema.constraint_column_usage AS ccu
    ON ccu.constraint_name = tc.constraint_name
    AND ccu.table_schema = tc.table_schema
LEFT JOIN information_schema.referential_constraints AS rc
    ON rc.constraint_name = tc.constraint_name
    AND rc.constraint_schema = tc.table_schema
WHERE tc.constraint_type = 'FOREIGN KEY'
    AND tc.table_name = 'template'
    AND kcu.column_name = 'categoryTypeId';

-- Check for orphaned data (templates with invalid categoryTypeId)
SELECT 
    'Orphaned Data Check' AS check_type,
    COUNT(*) AS orphaned_count,
    CASE 
        WHEN COUNT(*) = 0 THEN '✅ No orphaned data'
        ELSE '⚠️  Found ' || COUNT(*) || ' templates with invalid categoryTypeId'
    END AS status
FROM template t
WHERE t."categoryTypeId" IS NOT NULL
    AND NOT EXISTS (
        SELECT 1
        FROM category_type ct
        WHERE ct.id = t."categoryTypeId"
    );

\echo ''
\echo '✅ Category type migration completed!'
\echo ''
\echo '📋 Summary:'
\echo '   - category_type table: Created'
\echo '   - template.categoryTypeId column: Added'
\echo '   - Foreign key constraint: Created'
\echo '   - Indexes: Created'
\echo '   - Comments: Added'
\echo ''
\echo '💡 Next steps:'
\echo '   - Use the Category Type API to create category types'
\echo '   - Update existing templates to use categoryTypeId'
\echo ''

